SHOW DATABASES;

USE DATABASE CRUNCHBASE_BASIC_COMPANY_DATA;

SHOW SCHEMAS;

USE SCHEMA PUBLIC;

SHOW VIEWS;

SELECT * FROM ORGANIZATION_SUMMARY
LIMIT 10;

SELECT COUNT(*) AS Amount from ORGANIZATION_SUMMARY;

SELECT DISTINCT(TYPE) FROM ORGANIZATION_SUMMARY;

SELECT DISTINCT(ROLES) FROM ORGANIZATION_SUMMARY;

SELECT COUNTRY_CODE, COUNT(*) AS number_of_organizations
FROM ORGANIZATION_SUMMARY
GROUP BY COUNTRY_CODE
ORDER BY number_of_organizations desc;

SELECT COUNTRY_CODE, COUNT(*) AS number_of_organizations
FROM ORGANIZATION_SUMMARY
WHERE COUNTRY_CODE in ('SWE', 'GBR','USA')
GROUP BY COUNTRY_CODE
ORDER BY number_of_organizations desc;

SELECT CITY, COUNT(*) AS number_of_organizations
FROM ORGANIZATION_SUMMARY
WHERE CITY in ('Stockholm','Gothenburg')
GROUP BY CITY
ORDER BY number_of_organizations desc;


